### ISSUE TITLE
Overly specified setup.py requirements results in conflicts

### ISSUE THREAD

**Issue by IanHeywood** [IanHeywood/shadeMS#2]
```
(shade) ianh@nash:~/TKAT$ shadems --prefix=0GC --field=0 --xaxis=f --yaxis=a --col=DATA 1558743128_sdp_l0.full_1284.full_pol_GX_339-4_8SPW.ms
Traceback (most recent call last):
  File "/home/ianh/venv/shade/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2618, in requires
    deps.extend(dm[safe_extra(ext)])
KeyError: 'cmd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ianh/venv/shade/bin/shadems", line 4, in <module>
    __import__('pkg_resources').require('shadems==0.0.1')
  File "/home/ianh/venv/shade/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/home/ianh/venv/shade/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/home/ianh/venv/shade/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/ianh/venv/shade/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/home/ianh/venv/shade/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/ianh/venv/shade/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/home/ianh/venv/shade/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2621, in requires
    "%s has no such extra feature %r" % (self, ext)
pkg_resources.UnknownExtra: requests 2.22.0 has no such extra feature 'cmd'
```

**Comment by sjperkins** [comment]
Having looked at the setup.py, I think the package requirements are overly specified and could be significantly pruned.

For example, I don't see `requests` used anywhere in shadems itself. It may be used in other packages on which shadems is dependent, but it should be the responsibility of those packages to install requests appropriately.

More concretely, it should be possible to simply specify:

```python
# setup.py

requirements=[
...
'datashader[examples_extra]',
...
]
```

as the above will pull in the appropriate [`colorcet` and `holoviews` dependencies](https://github.com/pyviz/datashader/blob/c35f158be0f36599aacc4c9a18929242eec5e9c8/setup.py#L11-L59) required by datashader rather than specifying them in shadems.

From a brief glimpse at the code

https://github.com/IanHeywood/shadeMS/blob/dfb8b8330b8e91002c87cc742fc42c7ec3e3f397/setup.py#L6-L20

could probably be reduced to the following:

```python
requirements = [
"dask-ms[xarray]",
"datashader[examples_extra]",
"future",
"matplotlib>2.2.3; python_version >= '3.5'",
]
```

**Comment by IanHeywood** [comment]
@SpheMakh, shall I implement @sjperkins' suggestions?

**Comment by IanHeywood** [comment]
(Thanks Simon!)

**Comment by sjperkins** [comment]
No problem, glad to help. Also for future reference that in the following case:

```python
requirements = [
   'dask-ms[xarray]'
   'xarray',
]
```

the `xarray` dependency will override the `xarray` dependency in dask-ms, potentially leading to conflicts in the packaging system. This is also a good reason to avoid over-specifying requirements.

**Comment by SpheMakh** [comment]
yep, it's a wise suggestion.

**Comment by IanHeywood** [comment]
Thanks @SpheMakh, I haven't found the time to give this any attention.

Cheers.
